//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webApiRestRoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialT
    {
        public int id { get; set; }
        public string videoName { get; set; }
        public string videoId { get; set; }
    }
}
